#!/usr/bin/env python3
"""Validate and render artifacts derived from the canonical database schema."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
CANONICAL_SCHEMA = REPOSITORY_ROOT / "init" / "01_schema.sql"
HANDOFF_ENTRYPOINT = REPOSITORY_ROOT / "fund-db-handoff" / "schema.sql"
MIGRATIONS_DIR = REPOSITORY_ROOT / "migrations"
MIGRATED_SEARCH_FUNCTIONS = (
    "find_organization_relations",
    "find_overseas_strategies",
    "find_products",
)
HANDOFF_CONTENT = """-- Do not add schema definitions here.
-- init/01_schema.sql is the repository's canonical schema source.
-- psql resolves \\ir relative to this file, so this entrypoint works from any cwd.
\\set ON_ERROR_STOP on
\\ir ../init/01_schema.sql
"""

OWNER_POSTLUDE = r"""

-- Environment-specific ownership, generated by scripts/schema_artifacts.py.
\set schema_owner '{owner}'

SELECT format(
    'ALTER %s %I.%I OWNER TO %I;',
    CASE object.relkind
        WHEN 'r' THEN 'TABLE'
        WHEN 'p' THEN 'TABLE'
        WHEN 'S' THEN 'SEQUENCE'
        WHEN 'v' THEN 'VIEW'
        WHEN 'm' THEN 'MATERIALIZED VIEW'
    END,
    namespace.nspname,
    object.relname,
    :'schema_owner'
)
FROM pg_class object
JOIN pg_namespace namespace ON namespace.oid = object.relnamespace
WHERE namespace.nspname IN ('audit', 'core', 'meta', 'raw', 'search')
  AND object.relkind IN ('r', 'p', 'S', 'v', 'm')
ORDER BY namespace.nspname, object.relname
\gexec

SELECT format(
    'ALTER FUNCTION %I.%I(%s) OWNER TO %I;',
    namespace.nspname,
    procedure.proname,
    pg_get_function_identity_arguments(procedure.oid),
    :'schema_owner'
)
FROM pg_proc procedure
JOIN pg_namespace namespace ON namespace.oid = procedure.pronamespace
WHERE namespace.nspname IN ('audit', 'core', 'meta', 'raw', 'search')
ORDER BY namespace.nspname, procedure.proname, procedure.oid
\gexec

SELECT format(
    'ALTER SCHEMA %I OWNER TO %I;',
    namespace.nspname,
    :'schema_owner'
)
FROM pg_namespace namespace
WHERE namespace.nspname IN ('audit', 'core', 'meta', 'raw', 'search')
ORDER BY namespace.nspname
\gexec
"""


def function_definition(schema: str, name: str) -> str:
    """Extract one search function definition from the canonical schema."""
    start = schema.index(f"CREATE FUNCTION search.{name}(")
    end = schema.index("\n$$;", start) + len("\n$$;")
    return schema[start:end]


def validate() -> list[str]:
    """Return drift errors; an empty list means the schema layout is valid."""
    errors: list[str] = []
    canonical = CANONICAL_SCHEMA.read_text(encoding="utf-8")
    handoff = HANDOFF_ENTRYPOINT.read_text(encoding="utf-8")

    if handoff != HANDOFF_CONTENT:
        errors.append(
            "fund-db-handoff/schema.sql drifted: keep it as the canonical psql entrypoint"
        )
    if "CREATE FUNCTION search." in handoff or "CREATE TABLE " in handoff:
        errors.append("fund-db-handoff/schema.sql must not contain copied DDL")
    if "ALTER SCHEMA audit OWNER TO " in canonical or re.search(
        r"^ALTER (?:TABLE|VIEW|FUNCTION|SEQUENCE).* OWNER TO ",
        canonical,
        flags=re.MULTILINE,
    ):
        errors.append(
            "init/01_schema.sql contains environment-specific ownership metadata"
        )
    migrations = "\n".join(
        path.read_text(encoding="utf-8")
        for path in sorted(MIGRATIONS_DIR.glob("V*.sql"))
    )
    for name in MIGRATED_SEARCH_FUNCTIONS:
        expected = function_definition(canonical, name).replace(
            "CREATE FUNCTION", "CREATE OR REPLACE FUNCTION", 1
        )
        if expected not in migrations:
            errors.append(
                f"existing-DB migrations do not reproduce canonical search.{name}"
            )
    sale_view = canonical[canonical.index("CREATE OR REPLACE VIEW core.v_product_sale_availability AS"):]
    sale_view = sale_view[:sale_view.index("FROM decision;") + len("FROM decision;")]
    if sale_view not in migrations:
        errors.append("sale availability view drifted between canonical schema and migrations")
    return errors


def render(owner: str | None) -> str:
    """Render canonical DDL with optional environment-specific ownership."""
    canonical = CANONICAL_SCHEMA.read_text(encoding="utf-8")
    if owner is None:
        return canonical
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_$-]*", owner):
        raise ValueError("owner must be a single PostgreSQL role name")
    return canonical.rstrip() + OWNER_POSTLUDE.format(owner=owner) + "\n"


def main() -> int:
    """Validate schema drift or render a standalone schema artifact."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail on schema drift")
    parser.add_argument("--owner", help="append generated ALTER OWNER statements")
    parser.add_argument("--output", type=Path, help="standalone output path; default stdout")
    args = parser.parse_args()

    if args.check:
        errors = validate()
        if errors:
            for error in errors:
                print(f"schema drift: {error}", file=sys.stderr)
            return 1
        print("schema source-of-truth check passed")
        return 0

    try:
        rendered = render(args.owner)
    except ValueError as error:
        parser.error(str(error))
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
    else:
        sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
